version: "2"

services:
  
  mongodb:
    image: mongo:4.0
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=test123

  aladinexplorer:
    image: rost1337/aladinexplorer:latest
    ports: 
      - 3040:3040
      - 9615:9615
    restart: always
    links:
      - mongodb
    volumes:
      - ./config.js:/home/aladinexplorer/config.js

